# Generated by Django 5.1.4 on 2024-12-22 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0003_alter_borrowing_borrow_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={"verbose_name_plural": "Payments"},
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(verbose_name=datetime.date(2024, 12, 22)),
        ),
    ]
